import type { Metadata } from "next";
import { Abril_Fatface, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import PageScrollProgress from "@/components/PageScrollProgress";

export const abril_fatface = Abril_Fatface({
    weight: "400",
    preload: false,
    subsets: ["latin"],
    variable: "--font-abril_fatface",
});
export const poppins = Poppins({
    weight: "300",
    subsets: ["latin"],
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    "font-poppins",
                    abril_fatface.variable,
                    poppins.variable
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar />
                    {children}
                    <PageScrollProgress />
                </ThemeProvider>
            </body>
        </html>
    );
}
