export const performances_data = [
    {
        title: "Business ventures",
        text: [
            "West founded the record label and production company GOOD Music in 2004, in conjunction with Sony BMG, shortly after releasing his debut album, The College Dropout. West, alongside then-unknown Ohio singer John Legend and fellow Chicago rapper Common were the label's inaugural artists.[241] The label houses artists including West, Big Sean, Pusha T, Teyana Taylor, Yasiin Bey / Mos Def, D'banj and John Legend, and producers including Hudson Mohawke, Q-Tip, Travis Scott, No I.D., Jeff Bhasker, and S1. GOOD Music has released ten albums certified gold or higher by the Recording Industry Association of America (RIAA). In November 2015, West appointed Pusha T the new president of GOOD Music.[242]",
            "In August 2008, West revealed plans to open 10 Fatburger restaurants in the Chicago area; the first was set to open in September 2008 in Orland Park. The second followed in January 2009, while a third location is yet to be revealed, although the process is being finalized. His company, KW Foods LLC, bought the rights to the chain in Chicago.[243] Ultimately, in 2009, only two locations actually opened. In February 2011, West shut down the Fatburger located in Orland Park.[244]",
            "In January 2012, West announced his establishment of the creative content company Donda, named after his late mother.[245] In his announcement, West proclaimed that the company would 'pick up where Steve Jobs left off' Donda would operate as a 'design company' with a goal to 'make products and experiences that people want and can afford'.[246] In stating Donda's creative philosophy, West articulated the need to 'put creatives in a room together with like minds' in order to 'simplify and aesthetically improve everything we see, taste, touch, and feel.'[246] West is notoriously secretive about the company's operations, maintaining neither an official website nor a social media presence.[247][248] Contemporary critics have noted the consistent minimalistic aesthetic exhibited throughout Donda creative projects.[249][250][251]",
            "West expressed interest in starting an architecture firm in May 2013, saying 'I want to do product, I am a product person, not just clothing but water bottle design, architecture ... I make music but I shouldn't be limited to one place of creativity'[252][253] and then later in November 2013, delivering a manifesto on his architectural goals during a visit to Harvard Graduate School of Design.[254] In May 2018, West announced he was starting an architecture firm called Yeezy Home, which will act as an arm of his already successful Yeezy fashion label.[255] In June 2018, the first Yeezy Home collaboration was announced by designer Jalil Peraza, teasing an affordable concrete prefabricated home as part of a social housing project.[256][257]",
            "In March 2015, it was announced that West is a co-owner, with various other music artists, in the music streaming service Tidal. The service specialises in lossless audio and high definition music videos. Jay-Z acquired the parent company of Tidal, Aspiro, in the first quarter of 2015.[258] Sixteen artist stakeholders including Jay-Z, Rihanna, Beyoncé, Madonna, Chris Martin, Nicki Minaj co-own Tidal, with the majority owning a 3% equity stake.[259] In October 2022, in direct response to bans he received on Twitter and Instagram stemming from his antisemitic comments,[260] West reached an agreement in principle to acquire the alt-tech social network Parler for an undisclosed amount.[261][262] Parler and West mutually agreed to terminate the proposed deal in mid-November.[263]",
        ],
    },
    {
        title: "Philanthropy",
        text: [
            "West, alongside his mother, founded the Kanye West Foundation in Chicago in 2003, tasked with a mission to battle dropout and illiteracy rates, while partnering with community organizations to provide underprivileged youth access to music education.[264] In 2007, West and the Foundation partnered with Strong American Schools as part of their 'Ed in '08'campaign.[265][266] As spokesman for the campaign, West appeared in a series of PSAs for the organization, and hosted an inaugural benefit concert in August of that year.[267] In 2008, following the death of West's mother, the foundation was rechristened The Dr. Donda West Foundation.[264][268] The foundation ceased operations in 2011.[269] In 2013, Kanye West and friend Rhymefest founded Donda's House, Inc., a program aimed at helping at-risk Chicago youth.[270]",
            "West has contributed to hurricane relief in 2005 by participating in a Hurricane Katrina benefit concert after the storm had ravaged black communities in New Orleans[271] and in 2012 when he performed at a Hurricane Sandy benefit concert.[272] In January 2019, West donated $10 million towards the completion of the Roden Crater by American artist James Turrell.[273] In June 2020, in the wake of the murder of George Floyd and the following protests, he donated $2 million between the family of Floyd and other victims of police brutality, Ahmaud Arbery and Breonna Taylor. The donation funded legal fees for Arbery and Taylor's families, as well as establishing a 529 plan to fully cover college tuition for Floyd's daughter.",
        ],
    },
    {
        title: "Acting and filmmaking",
        text: [
            "West made cameo appearances as himself in the films State Property 2 (2005) and The Love Guru (2008),[275][276] and in an episode of the television show Entourage in 2007.[277] West provided the voice for 'Kenny West', a rapper, in the animated sitcom The Cleveland Show.[276] In 2009, he starred in the Spike Jonze-directed short film We Were Once a Fairytale (2009), playing himself acting belligerently while drunk in a nightclub.[278] West wrote, directed, and starred in the musical short film Runaway (2010), which heavily features music from My Beautiful Dark Twisted Fantasy.[96] The film depicts a relationship between a man, played by West, and a half-woman, half-phoenix creature.",
            "In 2012, West wrote and directed another short film, titled Cruel Summer, which premiered at the 2012 Cannes Film Festival in a custom pyramid-shaped screening pavilion featuring seven screens constructed for the film. The film was inspired by the compilation album of the same name. West made a cameo appearance in the comedy Anchorman 2: The Legend Continues (2013) as a MTV News representative in the film's fight scene.[citation needed] In September 2018, West announced the starting of a film production company named Half Beast, LLC.[280] A documentary shot over 21 years featuring footage of West's early days in Chicago through the death of his mother to his presidential run was announced to debut in 2021. Titled Jeen-Yuhs, it was acquired by Netflix for $30 million.",
        ],
    },
    {
        title: "Presidential campaigns",
        text: [
            "On July 4, 2020, West announced on Twitter that he would be running in the 2020 presidential election.[282][283] On July 7, West was interviewed by Forbes about his presidential run, where he announced that his running mate would be Wyoming preacher Michelle Tidball, and that he would run as an independent under the 'Birthday Party', explaining his decision of why he chose the name, saying, 'Because when we win, it's everybody's 'birthday'.'[284] West also said he no longer supported Trump because he 'hid in [a] bunker' during the COVID-19 pandemic.[285] Continuing, he said, 'You know? Obama's special. Trump's special. We say Kanye West is special. America needs special people that lead. Bill Clinton? Special. Joe Biden's not special.'",
            "Various political pundits speculated that West's presidential run was a publicity stunt to promote his latest music releases.[286] On July 15, 2020, official paperwork was filed with the Federal Election Commission for West, under the 'BDY' Party affiliation[287] amid claims that he was preparing to drop out.[288] West held his first rally that weekend, on July 19.[289] West aligned himself with the philosophy of a consistent life ethic, a tenet of Christian democracy.[290] His platform advocated for the creation of a culture of life, endorsing environmental stewardship, supporting the arts, buttressing faith-based organizations, restoring school prayer, providing for a strong national defense, and 'America First' diplomacy.[291] In July 2020, West told Forbes that he is ignorant on issues such as taxes and foreign policy.",
            "West conceded on Twitter on November 4, 2020.[293][294] He received 66,365 votes in the 12 states he had ballot access in, receiving an average of 0.32%. Reported write-in votes gave West an additional 3,931 votes across 5 states. In addition, the Roque De La Fuente / Kanye West ticket won 60,160 votes in California (0.34%).[295] According to Reuters, on January 4, 2021, a Kanye West-linked publicist pressured a Georgia election worker to confess to bogus charges of election tampering to assist Trump's claims of election interference.[296][297][298] In December 2021, The Daily Beast reported that West's presidential campaign received millions of dollars in services from a secret network of Republican operatives, payments to which the committee did not report. According to campaign finance experts, this was done to conceal a connection.",
            "West has stated his intentions to run for president again in the 2024 presidential election. In November 2019, he said at an event, 'When I run for president in 2024, we would've created so many jobs that I'm not going to run, I'm going to walk.' He was met with laughter from the audience.[301] On October 24, 2020, while running for president, West told Joe Rogan on his podcast that he would be open to running for Governor of California.[302] On May 19, 2021, Fox News reported that it had obtained a letter concerning an RFAI (Request for further information) from the Federal Election Commission regarding an exploratory presidential committee. West's representatives stated, 'Kanye West has not decided whether to become a candidate for president in the 2024 election, and the activity of the Kanye 2020 committee that prompted this RFAI is strictly exploratory.'[303] West said he approached former president Donald Trump and asked him if he would be interested in being his running mate.[304][305] On subsequent interviews, merchandise, and in songs lyrics, West would repeatedly insinuate that he will indeed run.[306] On November 20, 2022, Kanye announced his intention to run in 2024.[307] In October 2023, an attorney for West said that he 'is not a candidate for office in 2024'.",
        ],
    },
];
